### ISSUE TITLE
job manager crash due to "Bad credentials"

### ISSUE THREAD

**Issue by boegel** [EESSI/eessi-bot-software-layer#142]
We should make the communication with GitHub in `process_running_jobs` in the job manager a bit more robust, and retry in case something went wrong?
This could be some kind of rate limiting thing in GitHub (the job manager doesn't use a GitHub token)

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 715, in <module>
    main()
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 680, in main
    job_manager.process_running_jobs(known_jobs[rj])
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 351, in process_running_jobs
    pullrequest = repo.get_pull(int(pr_number))
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Repository.py", line 2792, in get_pull
    "GET", f"{self.url}/pulls/{number}"
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

tail of job manager log file when crash happened:
```
[20230115-T00:13:37] job manager main loop: iteration 3097
[20230115-T00:13:37] job manager main loop: known_jobs='3311'
[20230115-T00:13:37] run_subprocess(): 'get_current_jobs(): squeue command' by running '/usr/bin/squeue --long --user=bot' in directory '/mnt/shared/home/bot/eessi-bot-software-layer'
[20230115-T00:13:37] run_cmd(): Result for running '/usr/bin/squeue --long --user=bot' in 'None
           stdout 'Sun Jan 15 00:13:37 2023
             JOBID PARTITION     NAME     USER    STATE       TIME TIME_LIMI  NODES NODELIST(REASON)
              3311   compute eessi-bo      bot  RUNNING    9:02:11 UNLIMITED      1 fair-mastodon-c5-2xlarge-0001
'
           stderr ''
           exit code 0
[20230115-T00:13:37] job manager main loop: current_jobs='3311'
[20230115-T00:13:37] job manager main loop: new_jobs=''
[20230115-T00:13:37] job manager main loop: running_jobs='3311'
[20230115-T00:13:37] Found metadata file at /mnt/shared/home/bot/eessi-bot-software-layer/jobs/submitted/3311/_bot_job3311.metadata
```

**Comment by trz42** [comment]
Hmm, thought the job manager uses the key to create a temporary token. Maybe the token has expired (valid for one hour I believe). If that's the case, we would only need to ensure that the token is valid and renewed if not.

**Comment by boegel** [comment]
I've seen this happening again, I think we need to get this one fixed ASAP, since it causes quite a bit of delay...

I will try and take a look at what's going on.

**Comment by trz42** [comment]
Not sure these crashes are caused by the same issue. However, recent crashes are likely caused by a change included in #172. Particularly, the changes in lines 635 and 638 (see https://github.com/EESSI/eessi-bot-software-layer/commit/05c624333a5f8b4e759a162f98eea293c741a7a2#diff-204100f8e9605cbc08259c9326aa02e0986ff5a0e6328489d2533d09dc333107) result in wrong information written to the job metadatafile. This issue is addressed with #185

**Comment by boegel** [comment]
assuming this is indeed fixed by #185 (if not, we can re-open)

**Comment by boegel** [comment]
Seems like this problem is not fixed with the fix in #185, happened again.

<details>

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 640, in <module>
    main()
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 609, in main
    job_manager.process_running_jobs(current_jobs[rj])
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 373, in process_running_jobs
    repo = gh.get_repo(repo_name)
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/MainClass.py", line 330, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

</details>

Tail of `eessi_bot_job_manager.log` log file:

<details>

```
[20230626-T16:10:41] job manager main loop: iteration 7760
[20230626-T16:10:41] job manager main loop: known_jobs='5595,5594,5593,5592,5598,5597,5596'
[20230626-T16:10:41] run_subprocess(): 'get_current_jobs(): squeue command' by running '/usr/bin/squeue --long --user=bot' in directory '/mnt/shared/home/bot/eessi-bot-software-layer'
[20230626-T16:10:42] run_cmd(): Result for running '/usr/bin/squeue --long --user=bot' in 'None
           stdout 'Mon Jun 26 16:10:41 2023
             JOBID PARTITION     NAME     USER    STATE       TIME TIME_LIMI  NODES NODELIST(REASON)
              5595   compute bot-buil      bot  RUNNING    1:50:50 1-00:00:00      1 fair-mastodon-c5a-4xlarge-0002
              5594   compute bot-buil      bot  RUNNING    1:50:50 1-00:00:00      1 fair-mastodon-c5-4xlarge-0002
              5593   compute bot-buil      bot  RUNNING    1:50:50 1-00:00:00      1 fair-mastodon-c4-4xlarge-0003
              5592   compute bot-buil      bot  RUNNING    1:50:50 1-00:00:00      1 fair-mastodon-c4-4xlarge-0004
              5598   compute bot-buil      bot  RUNNING    1:49:50 1-00:00:00      1 fair-mastodon-c6g-4xlarge-0003
              5597   compute bot-buil      bot  RUNNING    1:49:50 1-00:00:00      1 fair-mastodon-c6g-4xlarge-0004
              5596   compute bot-buil      bot  RUNNING    1:49:50 1-00:00:00      1 fair-mastodon-c6a-4xlarge-0002
'
           stderr ''
           exit code 0
[20230626-T16:10:42] job manager main loop: current_jobs='5595,5594,5593,5592,5598,5597,5596'
[20230626-T16:10:42] job manager main loop: new_jobs=''
[20230626-T16:10:42] job manager main loop: running_jobs='5595,5594,5593,5592,5598,5597,5596'
[20230626-T16:10:42] Found metadata file at /mnt/shared/home/bot/eessi-bot-software-layer/jobs/submitted/5595/_bot_job5595.metadata
[20230626-T16:10:42] process_running_job(): found comment with id 1607591344
[20230626-T16:10:43] Found metadata file at /mnt/shared/home/bot/eessi-bot-software-layer/jobs/submitted/5594/_bot_job5594.metadata
[20230626-T16:10:43] process_running_job(): found comment with id 1607591303
[20230626-T16:10:43] Found metadata file at /mnt/shared/home/bot/eessi-bot-software-layer/jobs/submitted/5593/_bot_job5593.metadata
```

</details>

**Comment by trz42** [comment]
> Seems like this problem is not fixed with the fix in #185, happened again.

Looks like a different problem to me. Metadata file seems to be ok. PR comment exists. Would probably be good if all calls via PyGithub log a bit more information so debugging becomes easier.

**Comment by boegel** [comment]
Maybe the token expired when the job manager tried to update the comment, and it fails to detect this and obtain a new token first?

**Comment by boegel** [comment]
Happened again today:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 640, in <module>
    main()
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 609, in main
    job_manager.process_running_jobs(current_jobs[rj])
  File "/mnt/shared/home/bot/eessi-bot-software-layer/eessi_bot_job_manager.py", line 374, in process_running_jobs
    pullrequest = repo.get_pull(int(pr_number))
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Repository.py", line 2792, in get_pull
    "GET", f"{self.url}/pulls/{number}"
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Requester.py", line 355, in requestJsonAndCheck
    verb, url, parameters, headers, input, self.__customConnection(url)
  File "/mnt/shared/home/bot/.local/lib/python3.6/site-packages/github/Requester.py", line 378, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by trz42** [comment]
Possibly the following lines could be put into a `try: ... except: ...` block, and/or one could use some `retry` capability implemented elsewhere.

https://github.com/EESSI/eessi-bot-software-layer/blob/030c450ed0a556452f1dca79e6a2bfc5fc1792f7/eessi_bot_job_manager.py#L464-L465
