### ISSUE TITLE
event handler crashes when trying to construct `upload_cmd`

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#160]
This happened when testing #154 and, on purpose, the setting `upload_to_s3_script` was not renamed to `tarball_upload_script`. Instead of fixing just this issue, the bots' components should check if all necessary configuration settings are available. See also related issues #31, #112 and PR #85 

```
[20230306-T10:17:31] WARNING: A crash occurred!
Traceback (most recent call last):
  File "/mnt/shared/home/trz42/pilot.nessi/venv_bot_p38/lib64/python3.8/site-packages/pyghee/lib.py", line 170, in process_event
    self.handle_event(event_info, log_file=log_file)
  File "/mnt/shared/home/trz42/pilot.nessi/venv_bot_p38/lib64/python3.8/site-packages/pyghee/lib.py", line 102, in handle_event
    handler(event_info, log_file=log_file)
  File "/mnt/shared/home/trz42/pilot.nessi/PR154/eessi_bot_event_handler.py", line 118, in handle_pull_request_event
    handler(event_info, pr)
  File "/mnt/shared/home/trz42/pilot.nessi/PR154/eessi_bot_event_handler.py", line 93, in handle_pull_request_labeled_event
    deploy_built_artefacts(pr, event_info)
  File "/mnt/shared/home/trz42/pilot.nessi/PR154/tasks/deploy.py", line 447, in deploy_built_artefacts
    upload_tarball(job_dir, target, timestamp, repo_name, pr.number)
  File "/mnt/shared/home/trz42/pilot.nessi/PR154/tasks/deploy.py", line 234, in upload_tarball
    upload_cmd = ' '.join(cmd_args)
TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by trz42** [comment]
Checking configuration settings has been implemented.
