### ISSUE TITLE
Job manager crashes when it encounters a non-bot job

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#33]
Sometimes it is useful to run an (interactive) test job. Currently the job manager crashes with messages such as below when it encounters one of these jobs.

```
(venv_bot_p38) [trz42@mgmt eessi-bot-software-layer]$ ./job_manager.sh
job manager just started, logging to '/mnt/shared/home/trz42/pilot.nessi/eessi-bot-software-layer/eessi_bot_job_manager.log', processing job ids ''
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/shared/home/trz42/pilot.nessi/eessi-bot-software-layer/eessi_bot_job_manager.py", line 472, in <module>
    main()
  File "/mnt/shared/home/trz42/pilot.nessi/eessi-bot-software-layer/eessi_bot_job_manager.py", line 459, in main
    job_manager.process_finished_job(known_jobs[fj])
  File "/mnt/shared/home/trz42/pilot.nessi/eessi-bot-software-layer/eessi_bot_job_manager.py", line 262, in process_finished_job
    repo_name = metadata_pr['repo'] or ''
KeyError: 'repo'
```
This is very likely because of non-bot jobs lack the job's metadata file (named `_bot_jobJOBID.metadata`). The job manager could test if the file exists, and if not prints out a message and ignores the job.

**Comment by boegel** [comment]
Some progress was made in #63, but the job manager still crashes on non-bot jobs, when it tries to finish a job that is a non-bot job:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/shared/home/boegel/eessi-bot-software-layer/eessi_bot_job_manager.py", line 656, in <module>
    main()
  File "/mnt/shared/home/boegel/eessi-bot-software-layer/eessi_bot_job_manager.py", line 637, in main
    job_manager.process_finished_job(known_jobs[fj])
  File "/mnt/shared/home/boegel/eessi-bot-software-layer/eessi_bot_job_manager.py", line 349, in process_finished_job
    sym_dst = os.readlink(job_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/shared/home/boegel/eessi-bot-software-layer/jobs/submitted/3153'
```
