### ISSUE TITLE
Improve bot by handling errors / exceptions properly

### ISSUE THREAD

**Issue by trz42** [EESSI/eessi-bot-software-layer#6]
Currently the bot does not handle errors or exceptions. In the future, this is needed to ensure that the bot processes events reliably. Errors might be reported back such that mitigation measures could be taken.

For example, submitting a batch job could result in many errors for various reasons. Another example, could be that disk space is exceeded on a resource.

**Comment by trz42** [comment]
Very important issue. It might be split up in different ones being more focused, e.g., handling specific types of errors.

**Comment by boegel** [comment]
Things to check:

- exit codes of commands being run (see also #44)
- presence of expected directories, rather than just assuming they are there;
- unexpected errors for any I/O related actions, like changing to a directory, reading/write to a file, updating a comment in a GitHub PR, etc.

Two actions should be taken when a problem is detected: 1) most importantly, a (warning) log message should be emitted; 2) the problem should be reported somewhere. The latter should probably be done by adding a comment in the relevant PR, but it could go beyond that, for example sending an email to a list of email addresses, sending a message to a Slack channel (maybe the [official slack-sdk on PyPI](https://pypi.org/project/slack-sdk/) is useful here), etc.

**Comment by boegel** [comment]
In #56, the idea arose to make the `run_cmd` function raise a `RuntimeError` exception by default if the command being run has a non-zero exit code.
We should check if that's the best way forward, or if another (default) approach is better...

**Comment by trz42** [comment]
A seldom error, but it just hit a bot instance early today. Issue was that the job manager could not query Slurm, then it crashed with
```
Traceback (most recent call last):
  File "/cluster/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/cluster/software/Python/3.7.4-GCCcore-8.3.0/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/cluster/projects/nn9992k/pilot.nessi.no/TRZ42-bot-build-with-swl-pr216/eessi_bot_job_manager.py", line 715, in <module>
    main()
  File "/cluster/projects/nn9992k/pilot.nessi.no/TRZ42-bot-build-with-swl-pr216/eessi_bot_job_manager.py", line 644, in main
    current_jobs = job_manager.get_current_jobs()
  File "/cluster/projects/nn9992k/pilot.nessi.no/TRZ42-bot-build-with-swl-pr216/eessi_bot_job_manager.py", line 65, in get_current_jobs
    log_file=self.logfile,
  File "/cluster/projects/nn9992k/pilot.nessi.no/TRZ42-bot-build-with-swl-pr216/tools/__init__.py", line 49, in run_cmd
    raise RuntimeError(error_msg)
RuntimeError: run_cmd(): Error running '/usr/bin/squeue --long --user=thomarob' in 'None
           stdout 'Wed Feb 01 00:26:16 2023
'
           stderr 'slurm_load_jobs error: Socket timed out on send/recv operation
'
````

**Comment by trz42** [comment]
Bot has become much more resilient over time. So closing this "early-life" issue.
